push-api: true
metric-retention: 12h
app-port: 5000
federate-refresh-seconds: 60
log-level: INFO
pull:
  scrape-interval-seconds: 60
  endpoints:
    - alias: "clickhouse-container"
      endpoint: "http://127.0.0.1:9101/metrics"
      scrape-interval-seconds: 60